# Generated by Django 3.2.7 on 2022-04-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='region',
        ),
    ]
