# Generated by Django 3.2.7 on 2022-04-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_schema__initial_model_fields'),
        ('articles', '0004_remove_article_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='regions.Region'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
